/* Generated by Stage.js IDE on Mon Mar 20 2017 01:09:19 GMT-0700 (PDT)*/
(function(app) {
    app.view("User.Heavy.Nested", {
        template: "@view/user/heavy/nested.html",
        svg: {},
        editors: {},
    });
})(Application);