/* Generated by Stage.js IDE on Fri Jun 02 2017 13:55:58 GMT-0700 (PDT)*/
(function(app) {
    app.view("User.Newexport", {
        template: "@view/user/newexport.html",
        svg: {},
        editors: {},
        attributes: {
            "style": "height:718px;width:259px;"
        },
    });
})(Application);