/* Generated by Stage.js IDE on Mon Mar 20 2017 01:01:50 GMT-0700 (PDT)*/
(function(app) {
    app.view("User.Qwe", {
        template: "@view/user/qwe.html",
        svg: {},
        editors: {},
    });
})(Application);