/* Generated by Stage.js IDE on Mon Jun 05 2017 18:42:20 GMT-0700 (PDT)*/
(function(app) {
    app.view("User.Test", {
        template: "@view/user/test.html",
        data: {},
        svg: {},
        editors: {},
        attributes: {},
    });
})(Application);