/* Generated by Stage.js IDE on Tue Mar 21 2017 13:03:34 GMT-0700 (PDT)*/
(function(app) {
    app.view("User.Zxc", {
        template: "@view/user/zxc.html",
        svg: {},
        editors: {},
    });
})(Application);